name: kitchen
short_name: kitchen
background_color: "#fff"
theme_color: "#fff"
plugins:
  - jekyll-seo-tag
collections:
  meals:
    output: true
defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: default
  - scope:
      path: ""
      type: meals
    values:
      layout: default
